### PR TITLE
NgRx Entity implementation

### PR DESCRIPTION
**Pull request by lexcaraig**
Implemented entity generator.

* Update all the necessary files
* Added all the necessary files
* Update README.MD

### CODE REVIEW

**Comment by kmathy** [comment]
Excellent Work!! A big thank to you @lexcaraig !! ;-)

**Comment by lexcaraig** [comment]
Please. If this is ready. Update the npm. So we can install it with the latest version. :)

**Comment by kmathy** [comment]
Just need to update the readme with the latest updates, changelog, test,... And after that, I will publish :)

**Comment by lexcaraig** [comment]
@kmathy let me know. And just a little favor. Can you add a contributor section in readme? So I can show it to the interview. Hahaa. Thanks! Happy New Year!!

**Comment by kmathy** [comment]
Ahaha No problem, I understand! 
It is published and I ill add this famous section.

Happy New Year!! ✨ 

EDIT: Readme updated as well ;) Good luck for your interview!

**Pull request merged**
